export { useService, type UseFeathersServiceOptions } from './use-service'
export { useLocal } from './use-local'
export { useQueuePromise } from './event-queue-promise'
export { useServiceLocal } from './use-service-local-queries'
export { useServiceTemps } from './use-service-temps'
export { useServiceEvents } from './use-service-events'
export { useServiceClones } from './use-service-clones'
export { useServicePending } from './use-service-pending'
export { useServiceStorage } from './use-service-storage'
export { useServiceEventLocks } from './use-service-event-locks'
export { useServicePagination } from './use-service-pagination'
export { useServiceApiFeathers } from './use-service-api-feathers'

export * from './types'
