export type * from './types'
export type * from './use-service-store/types'
export type * from './use-find-get/types'

export { createVueClient } from './create-vue-client'
export { VueService } from './create-vue-service'
export { OFetch } from './feathers-ofetch'

export * from './hooks'
export * from './localstorage'
export * from './modeling'
export * from './use-auth'
export * from './use-find-get'
export * from './use-service-store'
export { useInstanceDefaults } from './utils'
